apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /mnt/persistent-volume
        containerPath: /mnt/persistent-volume
    extraPortMappings:
    - containerPort: 443
      hostPort: 443
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 8081
      hostPort: 8081
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 80
      hostPort: 80
      listenAddress: "127.0.0.1"
      protocol: TCP