apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: appservice-ns
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/persistent-volume"