apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddk8s-appservice-ext-k8se-build-service
  namespace: appservice-ns
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi